POST http://127.0.0.1:4000/purchaseOrder/create HTTP/1.1
content-type: application/json

{
	"purchaseOrder": { 
        "CardName":"",
        "CntctCode":"",
        "NumAtCard":"",
        //"DocCur":"MXN",
        "DocNum": "1",
        "DocDate": "20230412",
        "DocDueDate": "20230412",
        "TaxDate":"20230412",
        "U_ID_OV":"",
        "U_Agencia":"",
        "U_C_AA":"",
        "U_Ref_AA":"",
        "U_N_Capt":"",
        "CardCode": "CLI0002",
        "UDF_UUID":"",
        "U_N_Tarja":"489234",
        "U_FechaPago":"",
        "U_Naviera":"ALPASA",
        "U_Nombre_Consig":"Jaime",
        "U_Direccion_Consig":"This is the test",
        "U_Proveedor":"Jimmy",
        "U_C_Proveedor":"",
        "U_RFC":"RUSA1232",
        "U_R_Social":"12983",
        "U_Embarcador_Merc":"Garcia Inc",
        "U_Regimen":"01",
        "U_H_Solicitado":"",
        "U_Estatus_contenedor":"Buen estado",
        "U_P_MBV":"",
        "U_Aduana":"JIMMY",
        "U_DTA":"",
        "U_Patente":"",
        "U_V_Aduana":"",
        "U_ID_WMS":"12323FJAD"
    }, 
	"articles": [
		{
				"DocNum": "1",
				"LineItem": "0",
				"Price": "1",
				"Quantity":"1",
				"ItemCode": "SER-015",
                //"Dscription":"AB12",
                //"WhsCode":"01",
                "FreeTxt":"AB12",
                //"Rate":"12",
                //"RetCost":"700",
                "U_Booking":"AB12",
                "U_IMO":"AB12",
                "U_transporte":"AB12",
                "U_Placas":"AB12",
                "U_N_Operador":"TEXTO",
                "U_Bultos":"10",
                "U_Peso_Neto":"10",
                "U_Cont":"TEXTO",
                "U_V_Comercial":"700",
                "U_BL":"AB12",
                "U_E_Mercancia":"AB12",
                //"SerialNum":"AB12",
                "U_N_Pedimento":"AB12",
                "U_L_Mecancia_P":true,
                "U_L_Clave_Mercancia_P":"AB12",
                "U_L_Remitente":"AB12",
                "U_L_Clave_Pedimento":"AB12",
                "U_UMComercial":"AB12",
                "U_PaisOrigen":"TEXTO",
                "U_NoFactura":"AB12",
                "U_MontoUSD":"700",
                "U_Monto_IVA":"700",
                "U_Forma_pago_IVA":"700",
                "U_Tasa_IVA":"700",
                "U_C_U_Tarifa":"10",
                "U_U_M_Tarifa":"TEXTO",
                "U_COVE":"AB12",
                "U_Sec_pedimento":"10",
                "U_TCC":"10",
                "U_M_Comp":"700",
                "U_F_PCC":"AB12",
                "U_P_Vendedor":"TEXTO",
                "U_Lote":"AB12",
                "U_Seguros":"700",
                "U_Fletes":"700",
                "U_Embalajes":"700",
                "U_Otros":"700",
                "U_Incoterm":"AB12",
                "U_F_increm":"AB12",
                "U_FACTORME":"AB12",
                "U_Marca":"AB12",
                "U_Modelo":"AB12",
                "U_Serie":"AB12",
                "U_P_Comprador":"TEXTO",
                "U_FechaPedimento":"20230412",
                "U_PaisDestino":"TEXTO",
                "U_FraccionA":"1",
                "U_C_original":"10",
                "U_C_actual":"10",
                "U_M_D_original":"700",
                "U_M_D_actual":"700",
                "U_P_consumo":"12",
                "U_T_Tasa":"12",
                "U_M_IGI":"700",
                "U_FP_IGI":"AB12",
                "U_FActualizacion":"AB12",
                "U_IGI_actual":"10",
                "U_NSalida":"AB12",
                "U_Buque1":"AB12"
		},
		{
				"DocNum": "1",
				"LineItem": "1",
				"Price": "28",
				"Quantity":"1",
				"ItemCode": "SER-013",
                //"Description":"AB12",
                //"WhsCode":"A1",
                "FreeTxt":"AB12",
                //"Rate":"12",
                //"RetCost":"700",
                "U_Booking":"AB12",
                "U_IMO":"AB12",
                "U_transporte":"AB12",
                "U_Placas":"AB12",
                "U_N_Operador":"TEXTO",
                "U_Bultos":"10",
                "U_Peso_Neto":"10",
                "U_Cont":"TEXTO",
                "U_V_Comercial":"700",
                "U_BL":"AB12",
                "U_E_Mercancia":"AB12",
                //"SerialNum":"AB12",
                "U_N_Pedimento":"AB12",
                "U_L_Mecancia_P":true,
                "U_L_Clave_Mercancia_P":"AB12",
                "U_L_Remitente":"AB12",
                "U_L_Clave_Pedimento":"AB12",
                "U_UMComercial":"AB12",
                "U_PaisOrigen":"TEXTO",
                "U_NoFactura":"AB12",
                "U_MontoUSD":"700",
                "U_Monto_IVA":"700",
                "U_Forma_pago_IVA":"700",
                "U_Tasa_IVA":"700",
                "U_C_U_Tarifa":"10",
                "U_U_M_Tarifa":"TEXTO",
                "U_COVE":"AB12",
                "U_Sec_pedimento":"10",
                "U_TCC":"10",
                "U_M_Comp":"700",
                "U_F_PCC":"AB12",
                "U_P_Vendedor":"TEXTO",
                "U_Lote":"AB12",
                "U_Seguros":"700",
                "U_Fletes":"700",
                "U_Embalajes":"700",
                "U_Otros":"700",
                "U_Incoterm":"AB12",
                "U_F_increm":"AB12",
                "U_FACTORME":"AB12",
                "U_Marca":"AB12",
                "U_Modelo":"AB12",
                "U_Serie":"AB12",
                "U_P_Comprador":"TEXTO",
                "U_FechaPedimento":"20230412",
                "U_PaisDestino":"TEXTO",
                "U_FraccionA":"1",
                "U_C_original":"10",
                "U_C_actual":"10",
                "U_M_D_original":"700",
                "U_M_D_actual":"700",
                "U_P_consumo":"12",
                "U_T_Tasa":"12",
                "U_M_IGI":"700",
                "U_FP_IGI":"AB12",
                "U_FActualizacion":"AB12",
                "U_IGI_actual":"10",
                "U_NSalida":"AB12",
                "U_Buque1":"AB12"
		}
	]
}